### PR TITLE
Merging fixes before UM

### PR DESCRIPTION
**Pull request by mbaas2**

### CODE REVIEW

**Review by bpbecker — CHANGES_REQUESTED** [review]
1. SemVer has unlocalized values
2. Why do you have both Version and SemVer ? I don't see where Version is used in the code anymore. 
3. _LogStatus - MYrc is global
4. I REALLY object to having i and r as global names.

**Comment by mbaas2** [comment]
1,3,4: sorry, that should have been done before. I've localized them.
2. it's used by the UCMD System (which does not play well with SemVer, as it needs a number)

**Comment by bpbecker** [comment]
Please explain #2 - how is it used by the UCMD system?

**Comment by mbaas2** [comment]
````
      ]DEVOPS.DTest -?    
───────────────────────────────────────────────────────────────────────────────                                                                                                                                                      
                                                                                                                                                                                                                                     
]DEVOPS.DTest                                                                                                                                                                                                                        
Source: C:\Users\mbaas\Documents\MyUCMDs\DyalogBuild.dyalog                                                                                                                                                                          
Version: 1.85                                                                                                                                                                                                                        
Syntax: up to 999 arguments                                                                                                                                                                                                          
Accepts modifiers -SuccessValue= -clear[=] -coverage[=] -filter= -halt -init -loglvl= -off[=] -order= -quiet -repeat= -setup[=] -suite= -teardown[=] -testlog[=] -tests= -timeout= -trace -ts -verbose                               
 Modifier 'off' accepts only values "0", "1", "2"                                                                                                                                                                                    
                                                                                                                                                                                                                                     
Run (a selection of) functions named test_* from a namespace, file or directory | Version 1.85.4                                                                                                                                     
    ]DEVOPS.DTest {<ns>|<file>|<path>} [-halt] [-filter=string] [-off] [-quiet] [-repeat=n] [-loglvl=n] [-setup[=fn]] [-suite=file] [-teardown[=fn]] [-testlog=logfile] [-tests=] [-ts] [-timeout=t] [-trace] [-verbose] [-clear[=n]]
    [-init] [-order={0|1|"NumVec"}] -SuccessValue=...]                                                                                                                                                                               
]DEVOPS.DTest -?? ⍝ for more info                                                                                                                                                                                                    
````

The data shown after `Version`  is the output of the `Version` function.

**Pull request merged**
